name: research_project_MW_GMM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  
  - numpy>=1.25,<2
  - pandas
  - matplotlib
  - seaborn
  - astropy
  - tqdm
  - scipy
  - scikit-learn
  - h5py
  - pytest
  - fitsio
  - ipykernel
  - astroquery
  - dustmaps
  - galpy
  - plotly 
  - pip
  - pip:
      - pygmmis

